export default {
  imbg: require('../assets/images/glitter.png'),
  logo: require('../assets/images/logo.png'),
  homeBg: require('../assets/images/homeimbg.png'),
  circle: require('../assets/images/yellow.png'),
  chakra: require('../assets/images/chakra.png'),
  rashi1: require('../assets/images/rashi1.png'),
  star: require('../assets/images/star.png'),
  sparkle: require('../assets/images/sparkle.png'),
  rashi2: require('../assets/images/rashi2.png'),
  rashi3: require('../assets/images/rashi3.png'),
  rashi4: require('../assets/images/rashi4.png'),
  rashi5: require('../assets/images/rashi5.png'),
  rashi6: require('../assets/images/rashi6.png'),
  rashi7: require('../assets/images/rashi7.png'),
  rashi8: require('../assets/images/rashi8.png'),
  grouped: require('../assets/images/grouped.png'),
  grouped2: require('../assets/images/grouped2.png'),
  loginBg: require('../assets/images/loginBg.png'),
  loaderJson: require('../assets/images/loader.json'),
  grouped3: require('../assets/images/grouped3.png'),
  reportBg: require('../assets/images/reportBg.png'),
  planetBg: require('../assets/images/planetBg.png'),
  walletBg: require('../assets/images/walletbg.png'),
  offerSpark: require('../assets/images/offerspark.png'),
  coinSpark: require('../assets/images/coinspark.png'),
  Coins: require('../assets/images/coins.png'),
  BlackZodiacBg: require('../assets/images/blackzodiac.png'),
  AddUser: require('../assets/images/adduser.png'),
  CompatBg: require('../assets/images/compatbg.png'),
  CSparkle: require('../assets/images/diamondsparkle.png'),
  CompHeart: require('../assets/images/compheart.png'),

  Aquarius: require('../assets/images/aquarius.png'),
  Aries: require('../assets/images/aries.png'),
  Cancer: require('../assets/images/cancer.png'),
  Capricorn: require('../assets/images/capricorn.png'),
  Gemini: require('../assets/images/gemini.png'),
  Leo: require('../assets/images/leo.png'),
  Libra: require('../assets/images/libra.png'),
  Pisces: require('../assets/images/pisces.png'),
  Sagittarius: require('../assets/images/sagittarius.png'),
  Scorpio: require('../assets/images/scorpio.png'),
  Taurus: require('../assets/images/taurus.png'),
  Virgo: require('../assets/images/virgo.png'),


  NotificationBG: require('../assets/images/notification.png'),
};
