export const Routes = {    
    Home: 'Home',
    Wallet: 'Wallet',
    TransactionHistory: 'TransactionHistory',
    Notification: 'Notification',
    SettingScreen: 'SettingScreen',
    UserProfile: 'UserProfile',
    ContactUs: 'ContactUs',
    Profile: 'Profile',
    AiAstrologer: 'AI Astrologer',
    MyReports: 'MyReports',
    OnboardingScreen: 'OnboardingScreen',
    PdfViewer: 'PdfViewer',
    ChatHistory: 'ChatHistory',
    ChatScreen: 'ChatScreen',
    Compatibility: 'Compatibility',
    Report: 'Report',
    BottomTabNavigator: 'BottomTabNavigator',
}

// export const Routes = {
//     [RouteNames.Home]: 'HomeScreen',
//     [RouteNames.Wallet]: 'WalletScreen',
//     [RouteNames.TransactionHistory]: 'TransactionHistory',
//     [RouteNames.Notification]: 'Notification',
//     [RouteNames.Setting]: 'SettingScreen',
//     [RouteNames.UserProfile]: 'UserProfile',
//     [RouteNames.ContactUs]: 'ContactUs',
//     [RouteNames.Profile]: 'Profile',  
//     [RouteNames.AiAstrologer]: 'AiAstrologer',
//     [RouteNames.MyReports]: 'MyReports',
//     [RouteNames.OnboardingScreen]: 'OnboardingScreen',
//     [RouteNames.PdfViewer]: 'PdfViewer',
//     [RouteNames.ChatHistory]: 'ChatHistory',
//     [RouteNames.ChatScreen]: 'ChatScreen',
//     [RouteNames.Compatibility]: 'Compatibility',
//     [RouteNames.Report]: 'Report',
//     [RouteNames.BottomTabNavigator]: 'BottomTabNavigator',
// }